# Generated by Django 3.0.7 on 2020-07-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField()),
                ('ename', models.CharField(max_length=30)),
                ('ejob', models.CharField(max_length=30)),
                ('esal', models.FloatField()),
            ],
        ),
    ]
