# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-06 04:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnqDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=30)),
                ('mno', models.IntegerField()),
                ('agent', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=60)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='Property_Details',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Property_Location',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='Your_Name_REGISTRATION_REQUIRED',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 4, 48, 47, 331470, tzinfo=utc)),
        ),
    ]
