# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-06 05:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0004_auto_20200806_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 5, 16, 20, 120362, tzinfo=utc)),
        ),
    ]
